openapi: 3.2.0
info:
  title: Insights User Tagging API
  description: '# Overview

    Download our postman collection here.'
  version: 3.1.3
servers:
- url: https://findmoney-dev.fingoal.com/v3
  description: Insights API Development
- url: https://findmoney.fingoal.com/v3
  description: Insights API Production
security:
- Authentication: []
tags:
- name: User Tagging
  description: markdown/tagging.md
paths:
  /users/{userId}:
    get:
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID for the user you want to retrieve.
        schema:
          type: string
      - name: include_tagged_transactions
        in: header
        required: false
        deprecated: true
        schema:
          type: string
          description: This field has been deprecated. Tagged transactions are received automatically from the enrichment API. Set to true to include all of the user's tagged transactions in the response. By default, tagged transactions are not included.
      tags:
      - User Tagging
      summary: Get a User
      description: 'This endpoint runs on data sent to the Transaction Enrichment endpoints. Tagging is run in batches twice daily and thus not available immediately after posting transactions. Also, in order to receive user tags, transaction dates must be within the past 90 days.


        Fetches user and transaction tags for a specified user ID. Both endpoints return the same schema. Use the sync keyword to trigger a manual update on the transaction and user tags for a single user.'
      operationId: getOneUser
      security:
      - Authentication:
        - read
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - user
                properties:
                  user:
                    type: object
                    required:
                    - uid
                    properties:
                      client_id:
                        type: string
                        description: Your client ID.
                      id:
                        type: string
                        description: The user ID.
                      uid:
                        type: string
                        description: The user's ID.
                      uniqueId:
                        type: string
                        description: The user's unique ID in the format of `client_id:uid`.
                      lifetimeSavings:
                        type: number
                        description: The user's lifetime savings, if known.
                      registrationDate:
                        type: string
                        format: date-time
                        description: The date on which the user was registered with FinSight API.
                      subtenantId:
                        type: string
                        description: The user's subtenant ID.
                      tags:
                        description: The FinSight API tags that were applied to the user.
                        type: array
                        items:
                          type: string
                      totaltransactions:
                        type: number
                        description: The total number of transactions the user has in FinSight API.
                      transactionsSinceLastUpdate:
                        type: number
                        description: The number of transactions since the last time insights were run for the user.
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        transaction_id:
                          type: string
                          description: The ID of the transaction.
                        simple_description:
                          type: string
                          description: A human-readable, simplified description for the transaction.
                        original_description:
                          type: string
                          description: The originally-submitted description of the transaction.
                        category:
                          type: string
                          description: The category of the transaction.
                        amount:
                          type: number
                          description: The transaction's amount in USD.
                        date:
                          type: string
                          format: date-time
                          description: The date of the transaction.
                        tags:
                          type: array
                          items:
                            type: string
                            description: The tags that were applied to the transaction.
        '401':
          description: Unauthorized
        '404':
          description: User ID could not be found
  /users/{userId}/sync:
    get:
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID for the user you want to retrieve.
        schema:
          type: string
      - name: include_tagged_transactions
        in: header
        required: false
        deprecated: true
        schema:
          type: string
          description: This field has been deprecated. Tagged transactions are received automatically from the enrichment API. Set to true to include all of the user's tagged transactions in the response. By default, tagged transactions are not included.
      tags:
      - User Tagging
      summary: Trigger a User Tag Update
      description: 'This endpoint runs on data sent to the Transaction Enrichment endpoints. Tagging is run in batches twice daily and thus not available immediately after posting transactions. Also, in order to receive user tags, transaction dates must be within the past 90 days.


        Fetches user and transaction tags for a specified user ID. Both endpoints return the same schema. Use the sync keyword to trigger a manual update on the transaction and user tags for a single user.'
      operationId: getOneUserSync
      security:
      - Authentication:
        - enrichment
        - calls_to_action
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersUserIdGet200Response'
        '401':
          description: Unauthorized
        '404':
          description: User ID could not be found
  /users/tags/{guid}:
    get:
      parameters:
      - name: guid
        in: path
        required: true
        description: The guid for the updates you want to retrieve.
        schema:
          type: string
      tags:
      - User Tagging
      summary: Retrieve Updated Tags
      description: If you subscribe to the user tag status updates, you can retrieve them from this endpoint with the `guid` you received from the status update webhook. The tag updates will stay live at this endpoint for 24 hours.
      operationId: getUserTagUpdates
      security:
      - Authentication:
        - read
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookConfigurationsTestPostUSER_TAGS_DATA'
        '401':
          description: Unauthorized
        '404':
          description: User ID could not be found
components:
  schemas:
    WebhookConfigurationsTestPostUSER_TAGS_DATA:
      type: object
      properties:
        tenant_id:
          type: string
          description: The ID of the tenant for the users included in this update, if they are from a tenant environment.
        userTags:
          type: object
          properties:
            created:
              description: A list of the new user tags that were generated for this user since the last user tagging update. A full list of the user tags can be accessed [here](https://fingoal.com/tags-list).
              type: array
              items:
                type: object
                properties:
                  user_id:
                    description: The user who received this tag. Corresponds to whatever 'uid' you initially uploaded to the enrichment.
                    type: string
                    example: '409088'
                  user_tag_id:
                    description: The ID of the tag that has been applied.
                    type: integer
                    example: 61
                  tag_name:
                    description: The name of the tag that has been applied.
                    type: string
                    example: Home Improvement Loan
            deleted:
              description: A list of the user tags that were removed from this user since the last user tagging update.
              type: array
              items:
                type: object
                properties:
                  user_id:
                    description: The user who received this tag. Corresponds to whatever 'uid' you initially uploaded to the enrichment.
                    type: string
                    example: '409088'
                  user_tag_id:
                    description: The ID of the tag that has been removed.
                    type: integer
                    example: 46
                  tag_name:
                    description: The name of the tag that has been removed.
                    type: string
                    example: Movie Goer
            modified:
              description: For incremental (that is, scored) user tags. Contains all scoring changes for any incremental user tags that have received a score change since the last update.
              type: array
              items:
                type: object
                properties:
                  user_id:
                    description: The user who received this tag. Corresponds to whatever 'uid' you initially uploaded to the enrichment.
                    type: string
                    example: '409088'
                  user_tag_id:
                    description: The ID of the tag that has been updated.
                    type: integer
                    example: 46
                  tag_name:
                    description: The name of the tag that has been updated.
                    type: string
                    example: Movie Goer
                  previous_value:
                    description: The last value for this tag's score, prior to this update.
                    type: integer
                    example: 50
                  new_value:
                    description: The new value for this tag's score.
                    type: integer
                    example: 75
                  delta:
                    description: The amount by which this tag's score has changed. Can be negative or positive. Will be the difference between the new_value and previous_value fields.
                    type: integer
                    example: 25
  securitySchemes:
    Authentication:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://findmoney.fingoal.com/v3/authentication
          scopes:
            enrichment: Grants access to the transaction enrichment APIs.
