openapi: 3.2.0
info:
  title: Link Money Fastlink API
  description: The Link Money API is an authentication portal that allows multiple developers to access the same financial data from an aggregation API.
  version: 1.0.0
servers:
- url: https://link-money-dev.fingoal.dev
  description: Development server
security:
- BearerAuth: []
tags:
- name: Fastlink
  description: The Link Money API permits end users to link and get data from their bank accounts.
paths:
  /yodlee/fastlink/get:
    post:
      operationId: getFastlinkFourDetails
      summary: Retrieve FastLink details
      tags:
      - Fastlink
      description: Provides necessary details for developers to integrate FastLink4 into their applications without exposing sensitive credentials. Requires user-level authentication.
      security:
      - BearerAuth:
        - userId
        - tenantId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                loginName:
                  type: string
                  description: The ID of the user for whom the Fastlink 4 session belongs. This can be any string of your choosing, although it is best to associate it with the unique identifier in your own system that most corresponds to one actual individual person.
              required:
              - loginName
      responses:
        '200':
          description: FastLink4 details retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  fastlinkConfiguration:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        description: The user token for the FastLink4 frontend.
                      fastLinkURL:
                        type: string
                        format: uri
                        description: The tenant-specific URL to embed FastLink4 as an iframe.
        '401':
          description: Unauthorized. The user or tenant details are incorrect or do not have the necessary permissions.
        '403':
          description: Forbidden. Access is denied due to invalid credentials or access rights.
components:
  securitySchemes:
    BearerAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://link-money-dev.fingoal.dev/api/oauth/token
          scopes:
            tenantId: Varies according to the tenant you are trying to access.
